name: Reviewdog

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.10"
        activate-environment: true
        enable-cache: true

    - name: Install
      run: |
        uv sync --group checking

    - name: Output installed packages
      run: |
        uv pip freeze
    
    - name: Output dependency tree
      run: |
        uv pip tree

    - name: Apply formatters
      run: |
        black .
        blackdoc .
        isort .

    - name: Reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
