name: Reviewdog

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0

    - name: Install
      run: |
        uv sync --group checking --group pipdeptree

    - name: Output installed packages
      run: |
        uv pip freeze
    
    - name: Output dependency tree
      run: |
        uv run pipdeptree

    - name: Apply formatters
      run: |
        uv run black .
        uv run blackdoc .
        uv run isort .

    - name: Reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
