name: Reviewdog

on:
  pull_request:
    types: [opened, review_requested]

permissions:
  contents: read
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6

    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4  # v10.1.0
      with:
        python-version: '3.10'

    - name: Install
      run: |
        uv sync --group checking --group pipdeptree

    - name: Output installed packages
      run: |
        uv pip freeze

    - name: Output dependency tree
      run: |
        uv run pipdeptree

    - name: Apply formatters
      run: |
        uv run black .
        uv run blackdoc .
        uv run isort .

    - name: Reviewdog
      uses: reviewdog/action-suggester@6ba408415017b58ee944777db851caa3d2d451b7  # v1
      with:
        tool_name: formatters
