name: Sphinx

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0

    - name: Install Dependencies
      run: |
        uv sync --extra document --group pipdeptree

    - name: Output installed packages
      run: |
        uv pip freeze

    - name: Output dependency tree
      run: |
        uv run pipdeptree

    - name: Build Document
      run: |
        uv run make -C docs html

    - uses: actions/upload-artifact@v4
      with:
        name: built-html
        path: |
            docs/build/html
